"""Compact segmented progress bar for multi-step workflows."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/progress_bar.ipynb.

# %% auto #0
__all__ = ['render_step_progress', 'create_step_progress_renderer']

# %% ../../nbs/components/progress_bar.ipynb #c3
from dataclasses import dataclass
from typing import Callable, Optional, Sequence

from fasthtml.common import Div, FT

from cjm_fasthtml_tailwind.utilities.sizing import w, h
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex, flex_direction, flex_display
from cjm_fasthtml_tailwind.utilities.borders import border
from cjm_fasthtml_tailwind.utilities.transitions_and_animation import transition, duration
from cjm_fasthtml_tailwind.core.base import combine_classes

from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui, border_dui
from cjm_fasthtml_daisyui.utilities.border_radius import border_radius
from cjm_fasthtml_daisyui.components.feedback.tooltip import tooltip, tooltip_placement

from ..core.models import StepInfo
from ..core.config import StepProgressConfig

# %% ../../nbs/components/progress_bar.ipynb #c5
def _build_segment_fill_cls(
    idx: int,          # segment index
    current: int,      # current step index
    config: StepProgressConfig,  # rendering config
) -> str:              # combined CSS class string for the fill div
    """Build CSS classes for a segment's inner fill div."""
    base = combine_classes(h.full, transition.colors, duration('200'))
    if idx < current:
        return combine_classes(base, getattr(bg_dui, config.fill_bg))
    elif idx == current:
        return combine_classes(base, getattr(bg_dui, config.fill_bg).opacity(config.current_opacity))
    else:
        return str(base)

# %% ../../nbs/components/progress_bar.ipynb #c8
def _build_segment(
    step: StepInfo,    # step descriptor
    idx: int,          # segment index
    current: int,      # current step index
    config: StepProgressConfig,  # rendering config
) -> FT:               # FastHTML element for one segment
    """Build a single progress bar segment."""
    fill_cls = _build_segment_fill_cls(idx, current, config)
    
    # Separator border on all segments after the first
    sep_cls = combine_classes(
        border.l('1'), getattr(border_dui, config.separator_color)
    ) if idx > 0 else ''
    
    if config.show_tooltips:
        # Tooltip wrapper + inner fill div
        tip_pos = getattr(tooltip_placement, config.tooltip_position)
        wrapper_cls = combine_classes(tooltip, tip_pos, flex('1'), sep_cls)
        return Div(
            Div(cls=fill_cls),
            cls=wrapper_cls,
            data_tip=step.title,
        )
    else:
        # Single div, no tooltip
        segment_cls = combine_classes(flex('1'), h.full, fill_cls, sep_cls)
        return Div(cls=segment_cls)

# %% ../../nbs/components/progress_bar.ipynb #c11
def render_step_progress(
    steps: Sequence[StepInfo],              # ordered step definitions
    current_index: int,                     # 0-based index of the current step
    config: Optional[StepProgressConfig] = None,  # rendering config (defaults used if None)
) -> FT:                                    # the progress bar element
    """Render a compact segmented progress bar showing position in a multi-step workflow."""
    if config is None:
        config = StepProgressConfig()
    
    # Handle empty steps
    if not steps:
        return Div(id=config.id)
    
    # Clamp current_index to valid range
    current_index = max(0, min(current_index, len(steps) - 1))
    
    # Build track container classes
    track_cls = combine_classes(
        flex_display,
        flex_direction.row,
        w.full,
        h(config.height),
        getattr(border_radius, config.border_radius),
        getattr(bg_dui, config.track_bg),
    )
    
    # Build segments
    segments = [
        _build_segment(step, idx, current_index, config)
        for idx, step in enumerate(steps)
    ]
    
    return Div(*segments, cls=track_cls, id=config.id)

# %% ../../nbs/components/progress_bar.ipynb #c15
def create_step_progress_renderer(
    config: Optional[StepProgressConfig] = None,  # rendering config
) -> Callable:  # callable with signature (steps, current_index) -> FT
    """Create a progress renderer callback for StepFlow integration."""
    if config is None:
        config = StepProgressConfig()
    
    def _render(
        steps: Sequence[StepInfo],  # ordered step definitions
        current_index: int,         # 0-based current step index
    ) -> FT:                        # the progress bar element
        """Render step progress bar."""
        return render_step_progress(steps, current_index, config)
    
    return _render
