# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-fasthtml-step-progress',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-fasthtml-step-progress',
                'lib_path': 'cjm_fasthtml_step_progress'},
  'syms': { 'cjm_fasthtml_step_progress.components.progress_bar': { 'cjm_fasthtml_step_progress.components.progress_bar._build_segment': ( 'components/progress_bar.html#_build_segment',
                                                                                                                                           'cjm_fasthtml_step_progress/components/progress_bar.py'),
                                                                    'cjm_fasthtml_step_progress.components.progress_bar._build_segment_fill_cls': ( 'components/progress_bar.html#_build_segment_fill_cls',
                                                                                                                                                    'cjm_fasthtml_step_progress/components/progress_bar.py'),
                                                                    'cjm_fasthtml_step_progress.components.progress_bar.create_step_progress_renderer': ( 'components/progress_bar.html#create_step_progress_renderer',
                                                                                                                                                          'cjm_fasthtml_step_progress/components/progress_bar.py'),
                                                                    'cjm_fasthtml_step_progress.components.progress_bar.render_step_progress': ( 'components/progress_bar.html#render_step_progress',
                                                                                                                                                 'cjm_fasthtml_step_progress/components/progress_bar.py')},
            'cjm_fasthtml_step_progress.core.config': { 'cjm_fasthtml_step_progress.core.config.StepProgressConfig': ( 'core/config.html#stepprogressconfig',
                                                                                                                       'cjm_fasthtml_step_progress/core/config.py')},
            'cjm_fasthtml_step_progress.core.models': { 'cjm_fasthtml_step_progress.core.models.StepInfo': ( 'core/models.html#stepinfo',
                                                                                                             'cjm_fasthtml_step_progress/core/models.py')}}}
