"""Configuration dataclass for the step progress bar component."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/config.ipynb.

# %% auto #0
__all__ = ['StepProgressConfig']

# %% ../../nbs/core/config.ipynb #b3
from dataclasses import dataclass

# %% ../../nbs/core/config.ipynb #b5
@dataclass
class StepProgressConfig:
    """Rendering configuration for the step progress bar."""
    height: int = 3                     # Tailwind h-{value} scale (h-3 = 12px)
    track_bg: str = "base_300"          # bg_dui attribute for unfilled track
    fill_bg: str = "primary"            # bg_dui attribute for completed segments
    current_opacity: int = 60           # opacity % for current step segment
    border_radius: str = "field"        # border_radius attribute (field/box/selector)
    separator_color: str = "base_100"   # border_dui attribute for segment dividers
    show_tooltips: bool = True          # show step name tooltips on hover
    tooltip_position: str = "top"       # tooltip_placement attribute (top/bottom/left/right)
    id: str = "step-progress"           # HTML id for the progress bar container
