"""Data models for the step progress bar component."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/models.ipynb.

# %% auto #0
__all__ = ['StepInfo']

# %% ../../nbs/core/models.ipynb #a3
from dataclasses import dataclass

# %% ../../nbs/core/models.ipynb #a5
@dataclass
class StepInfo:
    """Describes a single step in a multi-step workflow."""
    title: str  # step name shown in tooltip on hover
